"use client";
import { Box, Typography } from "@mui/material";
import { SideMenu, TopMenu } from "../components/menu";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Box
          sx={{
            width: "100vw",
            minHeight: "100vh",
          }}
        >
          <Box display={{ xs: "none", lg: "block" }}>
            <TopMenu />
          </Box>
          <Box display={{ xs: "block", lg: "none" }}>
            <SideMenu />
          </Box>
          <Box sx={{ px: 10 }}>{children}</Box>
        </Box>
      </body>
    </html>
  );
}
